### ISSUE TITLE
Fail to build on MacOS

### ISSUE THREAD

**Issue by dpc** [dirs-dev/dirs-rs#22] opened 2019-07-05 06:38 UTC
```
   Compiling dirs v2.0.1
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:17:56
   |
17 | pub fn audio_dir()      -> Option<PathBuf> { dirs_sys::user_dir("MUSIC") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:18:56
   |
18 | pub fn desktop_dir()    -> Option<PathBuf> { dirs_sys::user_dir("DESKTOP") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:19:56
   |
19 | pub fn document_dir()   -> Option<PathBuf> { dirs_sys::user_dir("DOCUMENTS") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:20:56
   |
20 | pub fn download_dir()   -> Option<PathBuf> { dirs_sys::user_dir("DOWNLOAD") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:22:56
   |
22 | pub fn picture_dir()    -> Option<PathBuf> { dirs_sys::user_dir("PICTURES") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:23:56
   |
23 | pub fn public_dir()     -> Option<PathBuf> { dirs_sys::user_dir("PUBLICSHARE") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:24:56
   |
24 | pub fn template_dir()   -> Option<PathBuf> { dirs_sys::user_dir("TEMPLATES") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
error[E0425]: cannot find function `user_dir` in module `dirs_sys`
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-2.0.1/src/lin.rs:25:56
   |
25 | pub fn video_dir()      -> Option<PathBuf> { dirs_sys::user_dir("VIDEOS") }
   |                                                        ^^^^^^^^ not found in `dirs_sys`
```

**Comment by bbqsrc** [comment] 2019-07-10 09:04
It also fails to build on iOS for the same reason.

**Comment by soc** [comment] 2019-08-21 16:15
Is this resolved?

**Comment by francesca64** [comment] 2020-03-07 01:50
I can't reproduce this; `dirs` 2.0.2 works fine on macOS for me.

**Comment by soc** [comment] 2020-03-07 02:20
Thanks! Closing this – feel free to reopen if it appears again.

**Closed as completed by soc** 2020-03-07 02:20 UTC
